### ISSUE TITLE
if refresh fails while logged in, catch block never gets reached

### ISSUE THREAD

**Issue by kimkong88** [oleksiikhr/jwt-multiple-request-refresh-token#1]
Hi, not sure if you will ever see this, I was looking around for refresh token solution and I came across here.

Everything seems to be working fine then I realized sometimes interceptor does not work as intended.
>
             axios
                .post("/auth/refresh-tokens", {
                    refreshToken: auth.refreshToken,
                })
                .then(({ data }) => {
                    console.log("then");
                    store.dispatch(
                        refreshAuth({
                            accessToken: data.access.token,
                            refreshToken: data.refresh.token,
                        })
                    );
                    console.log("access", data.access.accessToken);
                    requestsToRefresh.forEach((cb) => cb(auth.accessToken));
                })
                .catch(() => {
                    console.log("catch");
                    store.dispatch(logOut());
                    requestsToRefresh.forEach((cb) => cb(null));
                })
                .finally(() => {
                    console.log("finally");
                    requestsToRefresh = [];
                    isRefreshRequesting = false;
                });
>

![image](https://user-images.githubusercontent.com/22599874/142714587-6187acec-ac91-4f25-bb1d-94ef2b97363c.png)

while debugging, I found out while user hits 401 error despite of having the token, it never reaches catch block, instead error will get intercepted by the interceptor and code starts from the beginning.
Have you had any issues like this?

Thanks!

**Comment by oleksiikhr** [comment]
Hi, I think it has to do with the fact that your `/refresh` endpoint status code may be returning a 401. What I wrote here is going to break logic.

That is:
- `/refresh` should not return a 401 status code in any case, otherwise it will fall into this section of the logic and will wait for itself: https://github.com/Alexeykhr/jwt-multiple-request-refresh-token/blob/master/index.html#L158
- The refresh should bypass the interceptions, which I think you can do with a new axios instance, or an additional attribute which will ignore your interceptions
- Or use third-party library, I was once recommended to use SuperTokens (https://news.ycombinator.com/item?id=22334752)

Hope that helped. If not, please give a little more context :)

**Comment by kimkong88** [comment]
Thank you for the comment. You are correct on my endpoint returning 401, I fixed that specific issue by returning 404 instead. I am still experiencing randomly getting kicked time to time, I have to investigate more to see. Thank you so much! I will take a look at SuperTokens.

**Comment by oleksiikhr** [comment]
Yes, but .. I think 404 server response is not the best option in this situation, at least 400 :)

**Comment by kimkong88** [comment]
Interesting, my logic was - if you cannot find a refresh token, then it should return either 401 or 404.. it is still valid request so 400 was out of option
